version: '2.0'
services:
  api:
    container_name: nest_api
    build: .
    ports:
      - ${PORT}:5000
    volumes:
      - .:/home/api
    command: sh -c npm run start:docker:prod
  database:
    container_name: nest_db
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
