version: '2.0'
services:
  api:
    container_name: nest_api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/home/api
  database:
    container_name: nest_db
    image: 'postgres:13'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: api
    ports:
      - 5432:5432
